#!/bin/bash
# chkconfig: 5 99 90
/performance/load-pf_ring

/opt/FMC/sbin64/cmSrv &
/opt/FMC/sbin64/coalSrv &
/opt/FMC/sbin64/cpuinfoSrv &
/opt/FMC/sbin64/cpustatSrv &
/opt/FMC/sbin64/fsSrv &
/opt/FMC/sbin64/ipmiSrv &
/opt/FMC/sbin64/irqSrv &
/opt/FMC/sbin64/logSrv &
/opt/FMC/sbin64/memSrv &
/opt/FMC/sbin64/nifSrv &
/opt/FMC/sbin64/osSrv &
/opt/FMC/sbin64/pcSrv &
/opt/FMC/sbin64/psSrv &
/opt/FMC/sbin64/smartSrv &
/opt/FMC/sbin64/tcpipSrv &
/opt/FMC/sbin64/tmSrv &
