#!/bin/bash

 usage(){
     HELP="
     usage: ./redirect desination_na62farmn file.pcap
     "
     echo -e $HELP
 }

 # If no arguments are provided...
 if [ $# -lt 2 ] ; then
     usage
     exit 1
 fi 

 #################
 #parsing arguments

	echo "assuming " $HOSTNAME " as sender"

	#Getting the absolute  path of the file
	FN=$(cd "$(dirname "$2")"; pwd)/$(basename "$2")

	#MAC1=`grep $1 -r address | awk '{print $3}'`
	#IP1=`grep $1 -r address | awk '{print $4}'`
	#MAC2=`grep $2 -r address | awk '{print $3}'`
	#IP2=`grep $2 -r address | awk '{print $4}'`

	MAC1=`cat /sys/class/net/dna0/address`
	IP1=`nslookup ${HOSTNAME}-in | tail -n 2 | head -n 1 | awk '{print $2}'`

	MAC2=`ssh $1 "cat /sys/class/net/dna0/address"`
	IP2=`nslookup ${1}-in | tail -n 2 | head -n 1 | awk '{print $2}'`
	
	echo "MAC ${MAC1} IP ${IP1}"
	echo "MAC ${MAC2} IP ${IP2}"

	extension="${FN##*.}"
	filename="${FN%.*}"
	#mapping packets direction needed to change the ips	
	#--mac has to be the machine mac that has recorded the packets 
	#i am supposing to work on a machine that receive and resend packets

	CACHEFILE=${filename}.cache
	OUTFILE=${filename}_FROM_${HOSTNAME}_TO_${1}_.pcap
	echo "Outfile: "${OUTFILE}
	echo "Outfile: "${CACHEFILE}

	#echo "tcpprep --mac=$MAC2 --reverse --pcap=$FN --cachefile=${CACHEFILE}"
	tcpprep --mac=$MAC1 --reverse --pcap=$FN --cachefile=${CACHEFILE}

	#--enet-smac=00:25:90:ed:d5:6 --enet-dmac=00:25:90:eb:dc:e4		\
	#echo "tcprewrite --endpoints=${IP2}:${IP2} --enet-smac=${MAC1} --enet-dmac=${MAC2} --infile=${FN} --cachefile=${CACHEFILE} --outfile=${OUTFILE}"
	tcprewrite --endpoints=${IP1}:${IP2} --enet-smac=${MAC1} --enet-dmac=${MAC2} --infile=${FN} --cachefile=${CACHEFILE} --outfile=${OUTFILE}



#README
#put the vanilla driver	then
#tcpdump -i eth2 -w file.pcap
#Convert ip and mac with this script
#put the vanilla driver	then
#tcpreplay --intf1=eth2 REDIRECT_file.pcap
